//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int MovieID { get; set; }
        public string Title { get; set; }
        public string DirectorsName { get; set; }
        public string Genre { get; set; }
        public string DateReleased { get; set; }
    }
}
