//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueryPracticeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public int MenuItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> Price { get; set; }
        public int CategoryID { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
